### ISSUE TITLE
Atividade - Aplicação Bancária

### ISSUE THREAD

**Issue by gabriel-guerra-amm** [gabriel-guerra/Atividades-POO#1]
# Orientações

[Link docs](https://docs.google.com/document/d/1siA5Q_NbTMVZvzErM1y5Ny4tp58tRJwiEQ-PVu7WJyQ/edit)

Crie uma aplicação com Java 17, Maven e JUnit 5 (5.9.3).
Utilize todos os conceitos apresentados em aula (tópicos no repositório do github).
Escreva testes unitários para comprovar a funcionalidade do software.
Códigos plagiados/copiados serão desconsiderados.

Aplicação Bancária

- [x] Criar contas para pessoas e empresas
- [x] Possibilidade de criar contas conjuntas (no máximo 2 pessoas do mesmo tipo com algum vínculo / ou união civil)
- [x] Conta Poupança deve ser aberta com valor mínimo de R$50,00
- [x] Conta Salário e Corrente não precisam de saldos iniciais.
- Ações:
   - [x] Transações bancárias (depósitos e pagamentos)
   - [x] Saldo
   - [x] Extrato por período
   - [x] Financiamento
   - [x] Aplicações
- [x] Montar cenários compatíveis para testes unitários

**Comment by gabriel-guerra** [comment]
> Extrato por período

Armazenar histórico de operações em um log para extrato; manter esse extrato ordenado para fins de consulta pela data.

**Comment by gabriel-guerra-amm** [comment]
> Extrato por período

Armazenar histórico de operações em um log para extrato

**Comment by gabriel-guerra-amm** [comment]
Classe Extrato:
- Data
- Saldo anterior
- Operação
- Valor
- Saldo final

**Comment by gabriel-guerra-amm** [comment]
Testes criar conta (conta poupança com e sem saldo)
- Conta individual (4)
- Conta conjunta (4)


Teste operações
- Depósito
- Pagamento
- Pagamento com valor maior que saldo
- Extrato em um prazo válido
- Extrato em prazo inválido
- Criar Aplicação
- Criar financiamento
